# 项目相关配置
datadevs-workspace:
  # 名称
  name: transfer-project
  # 版本
  version: 1.0.0
  # 版权年份
  copyrightYear: 2020
# 开发环境配置
server:
  # 服务器的HTTP端口，默认为80
  port: 8081
  servlet:
    # 应用的访问路径
    context-path: /
  tomcat:
    # tomcat的URI编码
    uri-encoding: UTF-8
    # tomcat最大线程数，默认为200
    max-threads: 800
    # Tomcat启动初始化的线程数，默认值25
    min-spare-threads: 30

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS

# Spring配置
spring:
  profiles:
    active: test
  # 模板引擎
  thymeleaf:
    mode: HTML
    encoding: utf-8
    # 禁用缓存
    cache: false
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  # 文件上传
  servlet:
    multipart:
      # 单个文件大小
      max-file-size:  10MB
      # 设置总上传的文件大小
      max-request-size:  20MB
  devtools:
    restart:
      # 热部署开关
      enabled: true

socket:
  port: 6000

transfer:
  programPath: C:\\Users\\Administrator\\Documents\\Main01.exe
  sourcePath: C:\\Download\\apache-tomcat-9.0.36\\\bin\\
  sourceName: PData36.xlsx
  sinkPath: C:\\Download\\apache-tomcat-9.0.36\\\bin\\Result.xlsx

request:
  httpUrl: http://123.56.96.214:8000/checkResult/getResult
